name: Generate and Publish Changelog

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
  release:
    type: [created]

permissions:
  contents: write

jobs:
  build-changelog:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Generate Changelog
      id: changelog
      shell: bash 
      run: |
        # detect the most recent version tag (tags must look like v1.2.3)
        last_tag=$(git describe --tags --abbrev=0 --match "v[0-9]*" 2>/dev/null || echo "")
        range="${last_tag:+$last_tag..}HEAD"

        echo "# Changelog" > CHANGELOG.md
        echo "All notable changes to this project will be documented in this file." >> CHANGELOG.md
        echo "The project is created and maintained by [Richard Koranteng](https://rkkoranteng.com), and adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html)." >> CHANGELOG.md
        echo >> CHANGELOG.md

        #echo "## ${last_tag} - $(date +%Y-%m-%d)" >> CHANGELOG.md
        echo "## ${last_tag}" >> CHANGELOG.md
        for section in "add|add:" "refactor|ref:" "fix|fix:" "delete|del:"
        do 
          IFS="|" read -r title prefix <<< "$section"
          commits=$(git log $range --pretty=format:"%h|%s|%an" | grep "|$prefix" || true)
          [ -z "$commits" ] &&continue
          #echo "### $title" >> CHANGELOG.md
          #echo "Commit message : $commits"
          echo "$(date +%Y-%m-%d) : $title - $commits" >> CHANGELOG.md
          
          while IFS='|' read -r hash msg author
          do
            clean_msg=${msg#"$prefix "}
            echo "- ${clean_msg} (${author})" >> CHANGELOG.md
          done <<< $commits
          
          echo >> CHANGELOG.md
        done
        
    - name: Commit & push
      run: |
        if [[ -n "$(git status --porcelain CHANGELOG.md)" ]]
        then
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@user.noreply.github.com"
          git add CHANGELOG.md
          git commit -m "docs: update CHANGELOG [skip ci]"
          git push
        else
          echo "No changelog update needed"
        fi
