name: Generate and Publish Changelog

on:
  push:
    branches: ["main"]
  workflow_dispatch:
  release:
    types: [created]

permissions:
  contents: write

jobs:
  build-changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate Changelog
        id: changelog
        shell: bash
        run: |
          # detect the most recent version tag (tags must look like v1.2.3)
          last_tag=$(git describe --tags --abbrev=0 --match "v[0-9]*" 2>/dev/null || echo "")
          range="${last_tag:+$last_tag..}HEAD"

          echo "# Changelog" > CHANGELOG.md
          echo "All notable changes to this project will be documented in this file." >> CHANGELOG.md
          echo >> CHANGELOG.md
          echo "The project is created and maintained by [Richard Koranteng](https://rkkoranteng.com), and adheres to [Calendar Versioning](https://calver.org/)." >> CHANGELOG.md
          echo >> CHANGELOG.md

          echo "## ${last_tag}" >> CHANGELOG.md

          for section in "Added|add:" "Changed|chg:" "Fixed|fix:" "Deleted|del:"
          do
            IFS="|" read -r title prefix <<< "$section"
            commits=$(git log $range --no-merges --date=short --pretty=format:"%ad|%s|%an" | grep -Ei "\|$prefix" | grep -Fv 'docs: update CHANGELOG [skip ci]' || true)
            [ -z "$commits" ] && continue

            echo "#### $title" >> CHANGELOG.md
            while IFS='|' read -r cdate msg author
            do
              clean_msg=$(echo "$msg" | sed -E "s/^$prefix[[:space:]]*//I")
              echo "- ${cdate} : ${clean_msg} (${author})" >> CHANGELOG.md
            done <<< "$commits"

            echo >> CHANGELOG.md
          done

      - name: Commit & push
        run: |
          if [[ -n "$(git status --porcelain CHANGELOG.md)" ]]; then
            git config user.name  "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add CHANGELOG.md
            git commit -m "docs: update CHANGELOG [skip ci]"
            git push
          else
            echo "No changelog update needed"
          fi
